### ISSUE TITLE
Support data frames

### ISSUE THREAD

**Issue by agrueneberg** [QuantGen/LinkedMatrix#1]
```R
> RowLinkedMatrix(mtcars, mtcars)[]
Error in Z[ini:end, ] <- x[[k]][TMP[, 3], j, drop = FALSE] : 
  incorrect number of subscripts on matrix
```

**Comment by gdlc** [comment]
On the one hand I think it would be good to support data frames. However, when it comes to computations, data frames are problematic. We cannot do crospprod, and functions like that with data frames. Hence, I think we should stick to types that are suitable for computations (e.g., numeric, integer). It may be better to leave data.frames for the @pheno  slot of a BGData.
